version: "3"
networks:
  inception_net:
services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - WP_DB_NAME=${WP_DB_NAME}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb_vol:/var/lib/mysql/
    networks:
      - inception_net
    restart: unless-stopped
  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    volumes:
      - wordpress_vol:/var/www/html/
    env_file:
      - .env
    networks:
      - inception_net
    restart: unless-stopped
  nginx:
    image: nginx
    build: 
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wordpress_vol:/var/www/html/
    networks:
      - inception_net
    restart: unless-stopped
volumes:
  mariadb_vol: 
    driver: local
    driver_opts: 
      type: none
      device: ${DB_VOL}
      o: bind
  wordpress_vol: 
    driver: local
    driver_opts: 
      type: none
      device: ${WP_VOL}
      o: bind
    